// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Persistence;

namespace scontracts.Api.Migrations
{
    /// <summary>
    /// ConsisContextModelSnapshot
    /// </summary>
    [DbContext(typeof(DataContext))]
    partial class ConsisContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// BuildModel
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository.Core.Domain.CAT_AVISOS", b =>
                {
                    b.Property<int>("Id_Aviso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id_Aviso");

                    b.ToTable("CAT_AVISOSRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Comercial", b =>
                {
                    b.Property<int>("ID_Comercial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ID_Comercial");

                    b.ToTable("Cat_ComercialRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_DiaFestivo", b =>
                {
                    b.Property<int>("ID_DiaFestivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_DiaFestivo");

                    b.ToTable("Cat_DiaFestivoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Documentacion", b =>
                {
                    b.Property<int>("ID_Documentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_Documentacion");

                    b.ToTable("Cat_DocumentacionRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Estatus", b =>
                {
                    b.Property<int>("ID_Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("ID_Estatus");

                    b.ToTable("Cat_EstatusRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_LDAP", b =>
                {
                    b.Property<int>("IdLDAP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("LDAP")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("IdLDAP");

                    b.ToTable("Cat_LDAPRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Modulos", b =>
                {
                    b.Property<int>("ID_Modulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_Modulo");

                    b.ToTable("Cat_ModulosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_ModulosMenuporRol", b =>
                {
                    b.Property<int>("ID_Menu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_Modulo")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pantalla")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.Property<long>("Seleccionado")
                        .HasColumnType("bigint");

                    b.HasKey("ID_Menu");

                    b.ToTable("Cat_ModulosMenuporRolRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Pais", b =>
                {
                    b.Property<int>("ID_Pais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ID_Pais");

                    b.ToTable("Cat_PaisRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Pantallas", b =>
                {
                    b.Property<int>("ID_Pantalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_Modulo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_Pantalla");

                    b.ToTable("Cat_PantallasRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Permisos", b =>
                {
                    b.Property<long>("ID_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ID_Modulo")
                        .HasColumnType("int");

                    b.Property<int>("ID_Pantalla")
                        .HasColumnType("int");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.HasKey("ID_Permiso");

                    b.ToTable("Cat_PermisosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Prioridad", b =>
                {
                    b.Property<int>("ID_Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_Prioridad");

                    b.ToTable("Cat_PrioridadRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Proveedor", b =>
                {
                    b.Property<int>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Cat_ProveedorRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Responsables", b =>
                {
                    b.Property<int>("ID_Responsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("ID_UnidadUsuario")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario_Registro")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_Responsable");

                    b.ToTable("Cat_ResponsablesRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Rol", b =>
                {
                    b.Property<int>("ID_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_Rol");

                    b.ToTable("Cat_RolRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_TipoAccion", b =>
                {
                    b.Property<int>("ID_TipoAccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID_TipoAccion");

                    b.ToTable("Cat_TipoAccionRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_TipoContrato", b =>
                {
                    b.Property<int>("ID_TipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ID_TipoSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_TipoContrato");

                    b.ToTable("Cat_TipoContratoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_TipoContratoSolicitud", b =>
                {
                    b.Property<int>("ID_TipoSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_TipoSolicitud");

                    b.ToTable("Cat_TipoContratoSolicitudRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_TipoDocumento", b =>
                {
                    b.Property<int>("ID_TipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("Liberado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_TipoDocumento");

                    b.ToTable("Cat_TipoDocumentoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_TipoMoneda", b =>
                {
                    b.Property<int>("ID_Moneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ID_Moneda");

                    b.ToTable("Cat_TipoMonedaRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Unidad", b =>
                {
                    b.Property<int>("ID_Unidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ID_Unidad");

                    b.ToTable("Cat_UnidadRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Unidad_Usuario", b =>
                {
                    b.Property<int>("ID_UnidadUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ID_UnidadUsuario");

                    b.ToTable("Cat_Unidad_UsuarioRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cat_Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("EnvioEmail")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCambioPwd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvioCorreo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInactiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimoIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Rol")
                        .HasColumnType("int");

                    b.Property<int>("ID_UnidadUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Local")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Puesto")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Socio")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("TelefonoExt")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID_Usuario");

                    b.ToTable("Cat_Usuario");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_ContratoUsuario", b =>
                {
                    b.Property<long>("ID_ContratoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<int>("ID_UsuarioAlta")
                        .HasColumnType("int");

                    b.HasKey("ID_ContratoUsuario");

                    b.ToTable("Cfg_ContratoUsuarioRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_Correos", b =>
                {
                    b.Property<int>("ID_Correo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(8000);

                    b.Property<int>("ID_Estatus")
                        .HasColumnType("int");

                    b.HasKey("ID_Correo");

                    b.ToTable("Cfg_CorreosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_PrioridadComplejidad", b =>
                {
                    b.Property<int>("ID_Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoContrato")
                        .HasColumnType("int");

                    b.Property<int>("Vuelta")
                        .HasColumnType("int");

                    b.HasKey("ID_Prioridad");

                    b.ToTable("Cfg_PrioridadComplejidadRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_PrioridadComplejidadSegunda", b =>
                {
                    b.Property<int>("ValorX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ValorY")
                        .HasColumnType("int");

                    b.Property<int>("ValorZ")
                        .HasColumnType("int");

                    b.HasKey("ValorX");

                    b.ToTable("Cfg_PrioridadComplejidadSegundaRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_PrioridadComplejidad_Historico", b =>
                {
                    b.Property<int>("ID_Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dias")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoContrato")
                        .HasColumnType("int");

                    b.Property<int>("Vuelta")
                        .HasColumnType("int");

                    b.HasKey("ID_Prioridad");

                    b.ToTable("Cfg_PrioridadComplejidad_HistoricoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.Cfg_UsuarioUnidadConsulta", b =>
                {
                    b.Property<int>("ID_UnidadConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID_UnidadUsuario")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_UnidadConsulta");

                    b.ToTable("Cfg_UsuarioUnidadConsultaRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.RefreshToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.ToTable("Cfg_RefreshToken");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Base_Unidades", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("F6")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("F7")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("Socio")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("UnidadNueva")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(510)")
                        .HasMaxLength(510);

                    b.HasKey("ID");

                    b.ToTable("TB_Base_UnidadesRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos", b =>
                {
                    b.Property<long>("ID_Contrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ContratoAdjunto")
                        .HasColumnType("bit");

                    b.Property<int>("DiasSegundaVuelta")
                        .HasColumnType("int");

                    b.Property<bool>("ElaboracionContrato")
                        .HasColumnType("bit");

                    b.Property<bool>("EnParoAbogado")
                        .HasColumnType("bit");

                    b.Property<bool>("EnParoSolicitante")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAceptacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvioFirma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRechazoCancelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimientoContrato")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<int>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<int>("ID_Moneda")
                        .HasColumnType("int");

                    b.Property<int>("ID_Prioridad")
                        .HasColumnType("int");

                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("ID_Responsable")
                        .HasColumnType("int");

                    b.Property<int>("ID_ResponsableJuridico")
                        .HasColumnType("int");

                    b.Property<int>("ID_Solicitante")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoContrato")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("ID_Unidad")
                        .HasColumnType("int");

                    b.Property<int>("ID_UnidadUsuario")
                        .HasColumnType("int");

                    b.Property<int>("ID_UsuarioRechazo")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazoCancelacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<bool>("TieneDocumentacion")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidoJuridico")
                        .HasColumnType("bit");

                    b.Property<int>("Vuelta")
                        .HasColumnType("int");

                    b.Property<int>("idIdioma")
                        .HasColumnType("int");

                    b.HasKey("ID_Contrato");

                    b.ToTable("TB_ContratosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Appointment", b =>
                {
                    b.Property<long>("ID_Contrato_Appointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_Appointment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Modify_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_Contrato_Appointment");

                    b.ToTable("TB_Contratos_AppointmentRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Detalle", b =>
                {
                    b.Property<long>("ID_Contrato_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CondicionesEspeciales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraprestacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescServiciosProductos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImporteTotalContrato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LugarFechaFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjetoNegociacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vigencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Contrato_Detalle");

                    b.ToTable("TB_Contratos_DetalleRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Documentacion", b =>
                {
                    b.Property<long>("ID_Archivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContenttType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_Documentacion")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("ID_Archivo");

                    b.ToTable("TB_Contratos_DocumentacionRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Email", b =>
                {
                    b.Property<long>("ID_Contrato_Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("Enviado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneroCorreo")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_Correo")
                        .HasColumnType("int");

                    b.HasKey("ID_Contrato_Email");

                    b.ToTable("TB_Contratos_EmailRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Finales", b =>
                {
                    b.Property<long>("ID_ContratoFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime>("FechaAdjunto")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Historico")
                        .HasColumnType("bit");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<long>("ID_HistorialContrato")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_ContratoFinal");

                    b.ToTable("TB_Contratos_FinalesRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Historial", b =>
                {
                    b.Property<long>("ID_Contrato_Historial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_UsuarioCambio")
                        .HasColumnType("int");

                    b.Property<string>("JuridicoAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("JuridicoNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("SolicitanteAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("SolicitanteNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("ID_Contrato_Historial");

                    b.ToTable("TB_Contratos_HistorialRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Seguimiento", b =>
                {
                    b.Property<long>("ID_Contrato_Seguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasAdelanto")
                        .HasColumnType("int");

                    b.Property<int>("DiasEstimados")
                        .HasColumnType("int");

                    b.Property<int>("DiasReales")
                        .HasColumnType("int");

                    b.Property<int>("DiasRetraso")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvioContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<bool>("ReCalculado")
                        .HasColumnType("bit");

                    b.HasKey("ID_Contrato_Seguimiento");

                    b.ToTable("TB_Contratos_SeguimientoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Contratos_Versiones", b =>
                {
                    b.Property<long>("ID_Contrato_Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenttType")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("ID_Contrato")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_TipoAccion")
                        .HasColumnType("int");

                    b.Property<int>("ID_UsuarioEnvio")
                        .HasColumnType("int");

                    b.Property<string>("NombreContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ID_Contrato_Version");

                    b.ToTable("TB_Contratos_VersionesRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_FolioConsecutivo", b =>
                {
                    b.Property<int>("IdFolioConsecutivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Ano")
                        .HasColumnType("bigint");

                    b.Property<int>("ID_TipoSolicitud")
                        .HasColumnType("int");

                    b.Property<long>("IdConsecutivo")
                        .HasColumnType("bigint");

                    b.HasKey("IdFolioConsecutivo");

                    b.ToTable("TB_FolioConsecutivoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Historial_Contratos", b =>
                {
                    b.Property<long>("ID_HistorialContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("ComentariosEstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(3500)")
                        .HasMaxLength(3500);

                    b.Property<bool>("ContratoAdjunto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("FechaVencimientoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("ID_Estatus")
                        .HasColumnType("int");

                    b.Property<int>("ID_Proveedor")
                        .HasColumnType("int");

                    b.Property<int>("ID_ResponsableJuridico")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoContrato")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoMoneda")
                        .HasColumnType("int");

                    b.Property<int>("ID_TipoSolicitud")
                        .HasColumnType("int");

                    b.Property<int>("ID_Unidad")
                        .HasColumnType("int");

                    b.Property<int>("ID_Unidad_Usuario")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("ObjetoContrato")
                        .IsRequired()
                        .HasColumnType("nvarchar(3000)")
                        .HasMaxLength(3000);

                    b.Property<string>("Solicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("ValidoJuridico")
                        .HasColumnType("bit");

                    b.HasKey("ID_HistorialContrato");

                    b.ToTable("TB_Historial_ContratosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Historial_Estatus", b =>
                {
                    b.Property<long>("Id_HistorialEstatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<DateTime>("FechaAplicado")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdContrato")
                        .HasColumnType("bigint");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAplico")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_HistorialEstatus");

                    b.ToTable("TB_Historial_EstatusRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Historial_Paros", b =>
                {
                    b.Property<long>("Id_HistorialParos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaParo")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdContrato")
                        .HasColumnType("bigint");

                    b.Property<int>("UltimoEstatus")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAplicoActivacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UsuarioAplicoParo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id_HistorialParos");

                    b.ToTable("TB_Historial_ParosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Historial_Prioridad", b =>
                {
                    b.Property<int>("IdHistorialPrioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdContrato")
                        .HasColumnType("bigint");

                    b.Property<int>("IdPrioridadAnterior")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridadNueva")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAplico")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdHistorialPrioridad");

                    b.ToTable("TB_Historial_PrioridadRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Historial_TipoContrato", b =>
                {
                    b.Property<int>("IdHistorialTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdContrato")
                        .HasColumnType("bigint");

                    b.Property<int>("IdTipoContratoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoContratoNueva")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAplico")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdHistorialTipoContrato");

                    b.ToTable("TB_Historial_TipoContratoRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Log", b =>
                {
                    b.Property<long>("Id_log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Control")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id_log");

                    b.ToTable("TB_LogRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Log2", b =>
                {
                    b.Property<long>("Id_log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Control")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id_log");

                    b.ToTable("TB_Log2Routines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Parametros", b =>
                {
                    b.Property<int>("ID_Parametro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TipoParametros")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("ID_Parametro");

                    b.ToTable("TB_ParametrosRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.TB_Usuario_Contrasenias", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pwd1")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd10")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd11")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd12")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd13")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd14")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd15")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd2")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd3")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd4")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd5")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd6")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd7")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd8")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Pwd9")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UltimoPwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID_Usuario");

                    b.ToTable("TB_Usuario_ContraseniasRoutines");
                });

            modelBuilder.Entity("Repository.Core.Domain.cat_Idioma", b =>
                {
                    b.Property<int>("idIdioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("idIdioma");

                    b.ToTable("cat_IdiomaRoutines");
                });
#pragma warning restore 612, 618
        }
    }
}
